# Generated by Django 4.2.16 on 2024-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
