# Generated by Django 4.2.16 on 2024-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_bonus_amount_user_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_user_leagth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
