# Generated by Django 4.2.16 on 2024-11-11 11:34

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_scrach_list_user_scrach_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django_mysql.models.ListTextField(models.CharField(max_length=20), blank=True, null=True, size=100)),
                ('user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
