# Generated by Django 4.2.16 on 2024-11-14 09:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrach_coupon',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='scratched_coupon_list',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=100),
        ),
    ]
