# Generated by Django 4.2.16 on 2024-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_scrach_coupon_read_user_scratched_coupon_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
