# Generated by Django 4.2.16 on 2024-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_match_details',
            name='disable_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
