# Generated by Django 4.2.16 on 2024-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_all_match_details_disable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_change_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
