# Generated by Django 4.2.16 on 2024-11-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_profile_change_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Add_Coin_In_Play',
            new_name='add_bonus',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Add_Coin_In_Winning',
            new_name='total_bonus',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Total_Play_Coin',
            new_name='total_wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Total_Winning_Coin',
        ),
    ]
