# Generated by Django 4.2.16 on 2024-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_add_coin_in_play_wallet_add_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_status',
            field=models.CharField(blank=True, default='KYC not submitted', max_length=255, null=True),
        ),
    ]
