# Generated by Django 4.2.16 on 2024-11-25 10:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_user_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, null=True, size=1000),
        ),
    ]
