# Generated by Django 4.2.16 on 2024-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw_amount',
            name='amount',
        ),
        migrations.AddField(
            model_name='withdraw_amount',
            name='amount_with_tds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw_amount',
            name='amount_without_tds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw_amount',
            name='tds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
