# Generated by Django 4.2.16 on 2024-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_amount',
            name='withdraw_status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
