# Generated by Django 4.2.16 on 2024-12-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_withdraw_amount_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_end_status',
            field=models.CharField(blank=True, default='Live', max_length=50, null=True),
        ),
    ]
