# Generated by Django 4.2.16 on 2024-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_match_match_end_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, default='pending', max_length=200, null=True),
        ),
    ]
