# Generated by Django 4.2.16 on 2024-12-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_amount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
