# Generated by Django 4.2.16 on 2024-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_pair_updated_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_query',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
