# Generated by Django 4.2.16 on 2024-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_player_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_with_captain',
            name='updated_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pair_with_captain_and_v_captain',
            name='updated_limit',
            field=models.IntegerField(default=0),
        ),
    ]
