# Generated by Django 4.2.16 on 2024-12-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_pair_with_captain_updated_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_match_details',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
