# Generated by Django 4.2.16 on 2024-12-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_all_match_details_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_query',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='user_query',
            name='message',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
