# Generated by Django 4.2.16 on 2025-01-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_user_query_timestamp_alter_user_query_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_deposited_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_profit_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
