# Generated by Django 4.2.16 on 2025-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_all_match_details_pool_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_withdrawal_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
