# Generated by Django 4.2.16 on 2025-01-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_user_total_withdrawal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_withdrawal_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
