---
- name: Setup Docker, Docker Compose, and clone Git repo
  hosts: all
  become: yes

  vars:
    docker_compose_version: "v2.27.0"
    git_repo_url: "https://github.com/your-user/your-repo.git"
    clone_dest: "/opt/your-repo"

  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

   - name: Remove broken Ansible PPA on Ubuntu 24.04
      apt_repository:
         repo: ppa:ansible/ansible
         state: absent
         

    - name: Clone Git repository
      git:
        repo: "{{https://github.com/TirthMesariya/Krinik.in.git }}"
        dest: "{{ /home/tirth/ }}"
        update: yes

    - name: Run Docker Compose
      command: docker-compose up --build -d
      args:
        chdir: /home/tirth/Krinik.in

