name: Deploy with Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: install ansible on ubuntu
        run: |
             sudo apt update && sudo apt upgrade -y
              sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
             sudo mkdir -p /etc/ansible
             sudo touch /etc/ansible/hosts
             sudo touch /etc/ansible/ansible.cfg
             sudo nano /etc/ansible/hosts

      - name: Run Ansible Playbook run
        run:  ansible-playbook deployment.yml

    
