name: Deploy with Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

 
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ansible-playbook deployment.yml -i inventory.ini


    
